### ISSUE TITLE
GNU social/StatusNet: Can't authorize on servers with unsupported SSL certs

### ISSUE THREAD

**Issue by jeroenpraat** [friendica/red-addons#23]
Probably the same issue as with Libertree before, so probably needs the same fix, but after examining statusnet.php I could not find the precise string. 

I can authorize on GNU social servers with HTTP and with normal supported/trusted SSL certs, but not with wrongly configured certs and alternative certs, like CAcert.

BTW: This problem was also before my last commit. I tested it to make sure it was not related.

**Comment by friendica** [comment]
Should be working - please test.

**Comment by ghost** [comment]
Yes works, forgot to test it. Thanks.

**Comment by ghost** [comment]
This issue was moved to redmatrix/redmatrix-addons#2
