### ISSUE TITLE
Startpage plugin does not display any settings

### ISSUE THREAD

**Issue by pafcu** [friendica/red-addons#29]
After activating the startpage pluing it is not shown under "Plugin Features", and navigating to the plugin page does not show any settings.

**Comment by friendica** [comment]
Available under personal Settings -> Feature Settings. Plugin Features is available on select plugins for admin configuration. This plugin does not require admin configuration.

**Comment by ghost** [comment]
This issue was moved to redmatrix/redmatrix-addons#3
