### ISSUE TITLE
Gnusocial/Statusnet errors

### ISSUE THREAD

**Issue by Keith2** [friendica/red-addons#36]
PHP Warning:  Invalid argument supplied for foreach() in /var/www/red.wf/addon/statusnet/statusnet.php on line 791
Occurs when the plugin has been enabled, settings in admin entered but no one is using it.

Next, when trying to use it
In Feature Settings, Send public postings to GNU social by default cannot be set.

**Comment by friendica** [comment]
The rand function should be fixed. settings_post is a mess and requires somebody to spend some time and sort it out. Basically there are a series of cascading if/else statements and the conditions necessary to store the post-by-default setting are cancelled out by an earlier 'else'  and the statement to store the result is never reached.

**Comment by ghost** [comment]
This issue was moved to redmatrix/redmatrix-addons#5
